// Generated by gencpp from file ros_x_habitat/EvalEpisodeRequest.msg
// DO NOT EDIT!


#ifndef ROS_X_HABITAT_MESSAGE_EVALEPISODEREQUEST_H
#define ROS_X_HABITAT_MESSAGE_EVALEPISODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_x_habitat
{
template <class ContainerAllocator>
struct EvalEpisodeRequest_
{
  typedef EvalEpisodeRequest_<ContainerAllocator> Type;

  EvalEpisodeRequest_()
    : episode_id_last()
    , scene_id_last()  {
    }
  EvalEpisodeRequest_(const ContainerAllocator& _alloc)
    : episode_id_last(_alloc)
    , scene_id_last(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _episode_id_last_type;
  _episode_id_last_type episode_id_last;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _scene_id_last_type;
  _scene_id_last_type scene_id_last;





  typedef boost::shared_ptr< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EvalEpisodeRequest_

typedef ::ros_x_habitat::EvalEpisodeRequest_<std::allocator<void> > EvalEpisodeRequest;

typedef boost::shared_ptr< ::ros_x_habitat::EvalEpisodeRequest > EvalEpisodeRequestPtr;
typedef boost::shared_ptr< ::ros_x_habitat::EvalEpisodeRequest const> EvalEpisodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator1> & lhs, const ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.episode_id_last == rhs.episode_id_last &&
    lhs.scene_id_last == rhs.scene_id_last;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator1> & lhs, const ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_x_habitat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ac0e35740d3cb94d954674abbd9cf6c";
  }

  static const char* value(const ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ac0e35740d3cb94ULL;
  static const uint64_t static_value2 = 0xd954674abbd9cf6cULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_x_habitat/EvalEpisodeRequest";
  }

  static const char* value(const ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string episode_id_last\n"
"string scene_id_last\n"
;
  }

  static const char* value(const ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.episode_id_last);
      stream.next(m.scene_id_last);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EvalEpisodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_x_habitat::EvalEpisodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "episode_id_last: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.episode_id_last);
    s << indent << "scene_id_last: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.scene_id_last);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_X_HABITAT_MESSAGE_EVALEPISODEREQUEST_H
