// Generated by gencpp from file ros_x_habitat/EvalEpisode.msg
// DO NOT EDIT!


#ifndef ROS_X_HABITAT_MESSAGE_EVALEPISODE_H
#define ROS_X_HABITAT_MESSAGE_EVALEPISODE_H

#include <ros/service_traits.h>


#include <ros_x_habitat/EvalEpisodeRequest.h>
#include <ros_x_habitat/EvalEpisodeResponse.h>


namespace ros_x_habitat
{

struct EvalEpisode
{

typedef EvalEpisodeRequest Request;
typedef EvalEpisodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EvalEpisode
} // namespace ros_x_habitat


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_x_habitat::EvalEpisode > {
  static const char* value()
  {
    return "4cf4a4cf4a1d60db72496f8e3635a2d3";
  }

  static const char* value(const ::ros_x_habitat::EvalEpisode&) { return value(); }
};

template<>
struct DataType< ::ros_x_habitat::EvalEpisode > {
  static const char* value()
  {
    return "ros_x_habitat/EvalEpisode";
  }

  static const char* value(const ::ros_x_habitat::EvalEpisode&) { return value(); }
};


// service_traits::MD5Sum< ::ros_x_habitat::EvalEpisodeRequest> should match
// service_traits::MD5Sum< ::ros_x_habitat::EvalEpisode >
template<>
struct MD5Sum< ::ros_x_habitat::EvalEpisodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_x_habitat::EvalEpisode >::value();
  }
  static const char* value(const ::ros_x_habitat::EvalEpisodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_x_habitat::EvalEpisodeRequest> should match
// service_traits::DataType< ::ros_x_habitat::EvalEpisode >
template<>
struct DataType< ::ros_x_habitat::EvalEpisodeRequest>
{
  static const char* value()
  {
    return DataType< ::ros_x_habitat::EvalEpisode >::value();
  }
  static const char* value(const ::ros_x_habitat::EvalEpisodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_x_habitat::EvalEpisodeResponse> should match
// service_traits::MD5Sum< ::ros_x_habitat::EvalEpisode >
template<>
struct MD5Sum< ::ros_x_habitat::EvalEpisodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_x_habitat::EvalEpisode >::value();
  }
  static const char* value(const ::ros_x_habitat::EvalEpisodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_x_habitat::EvalEpisodeResponse> should match
// service_traits::DataType< ::ros_x_habitat::EvalEpisode >
template<>
struct DataType< ::ros_x_habitat::EvalEpisodeResponse>
{
  static const char* value()
  {
    return DataType< ::ros_x_habitat::EvalEpisode >::value();
  }
  static const char* value(const ::ros_x_habitat::EvalEpisodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_X_HABITAT_MESSAGE_EVALEPISODE_H
