// Generated by gencpp from file ros_x_habitat/GetAgentPose.msg
// DO NOT EDIT!


#ifndef ROS_X_HABITAT_MESSAGE_GETAGENTPOSE_H
#define ROS_X_HABITAT_MESSAGE_GETAGENTPOSE_H

#include <ros/service_traits.h>


#include <ros_x_habitat/GetAgentPoseRequest.h>
#include <ros_x_habitat/GetAgentPoseResponse.h>


namespace ros_x_habitat
{

struct GetAgentPose
{

typedef GetAgentPoseRequest Request;
typedef GetAgentPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAgentPose
} // namespace ros_x_habitat


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_x_habitat::GetAgentPose > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::ros_x_habitat::GetAgentPose&) { return value(); }
};

template<>
struct DataType< ::ros_x_habitat::GetAgentPose > {
  static const char* value()
  {
    return "ros_x_habitat/GetAgentPose";
  }

  static const char* value(const ::ros_x_habitat::GetAgentPose&) { return value(); }
};


// service_traits::MD5Sum< ::ros_x_habitat::GetAgentPoseRequest> should match
// service_traits::MD5Sum< ::ros_x_habitat::GetAgentPose >
template<>
struct MD5Sum< ::ros_x_habitat::GetAgentPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_x_habitat::GetAgentPose >::value();
  }
  static const char* value(const ::ros_x_habitat::GetAgentPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_x_habitat::GetAgentPoseRequest> should match
// service_traits::DataType< ::ros_x_habitat::GetAgentPose >
template<>
struct DataType< ::ros_x_habitat::GetAgentPoseRequest>
{
  static const char* value()
  {
    return DataType< ::ros_x_habitat::GetAgentPose >::value();
  }
  static const char* value(const ::ros_x_habitat::GetAgentPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_x_habitat::GetAgentPoseResponse> should match
// service_traits::MD5Sum< ::ros_x_habitat::GetAgentPose >
template<>
struct MD5Sum< ::ros_x_habitat::GetAgentPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_x_habitat::GetAgentPose >::value();
  }
  static const char* value(const ::ros_x_habitat::GetAgentPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_x_habitat::GetAgentPoseResponse> should match
// service_traits::DataType< ::ros_x_habitat::GetAgentPose >
template<>
struct DataType< ::ros_x_habitat::GetAgentPoseResponse>
{
  static const char* value()
  {
    return DataType< ::ros_x_habitat::GetAgentPose >::value();
  }
  static const char* value(const ::ros_x_habitat::GetAgentPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_X_HABITAT_MESSAGE_GETAGENTPOSE_H
