// Generated by gencpp from file ros_x_habitat/GetAgentTimeResponse.msg
// DO NOT EDIT!


#ifndef ROS_X_HABITAT_MESSAGE_GETAGENTTIMERESPONSE_H
#define ROS_X_HABITAT_MESSAGE_GETAGENTTIMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_x_habitat
{
template <class ContainerAllocator>
struct GetAgentTimeResponse_
{
  typedef GetAgentTimeResponse_<ContainerAllocator> Type;

  GetAgentTimeResponse_()
    : agent_time(0.0)  {
    }
  GetAgentTimeResponse_(const ContainerAllocator& _alloc)
    : agent_time(0.0)  {
  (void)_alloc;
    }



   typedef float _agent_time_type;
  _agent_time_type agent_time;





  typedef boost::shared_ptr< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAgentTimeResponse_

typedef ::ros_x_habitat::GetAgentTimeResponse_<std::allocator<void> > GetAgentTimeResponse;

typedef boost::shared_ptr< ::ros_x_habitat::GetAgentTimeResponse > GetAgentTimeResponsePtr;
typedef boost::shared_ptr< ::ros_x_habitat::GetAgentTimeResponse const> GetAgentTimeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator1> & lhs, const ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.agent_time == rhs.agent_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator1> & lhs, const ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_x_habitat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "823e9883d7a51ebd6a56062eea85e4b1";
  }

  static const char* value(const ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x823e9883d7a51ebdULL;
  static const uint64_t static_value2 = 0x6a56062eea85e4b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_x_habitat/GetAgentTimeResponse";
  }

  static const char* value(const ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 agent_time\n"
;
  }

  static const char* value(const ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agent_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAgentTimeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_x_habitat::GetAgentTimeResponse_<ContainerAllocator>& v)
  {
    s << indent << "agent_time: ";
    Printer<float>::stream(s, indent + "  ", v.agent_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_X_HABITAT_MESSAGE_GETAGENTTIMERESPONSE_H
