// Generated by gencpp from file ros_x_habitat/PointGoalWithGPSCompass.msg
// DO NOT EDIT!


#ifndef ROS_X_HABITAT_MESSAGE_POINTGOALWITHGPSCOMPASS_H
#define ROS_X_HABITAT_MESSAGE_POINTGOALWITHGPSCOMPASS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_x_habitat
{
template <class ContainerAllocator>
struct PointGoalWithGPSCompass_
{
  typedef PointGoalWithGPSCompass_<ContainerAllocator> Type;

  PointGoalWithGPSCompass_()
    : header()
    , distance_to_goal(0.0)
    , angle_to_goal(0.0)  {
    }
  PointGoalWithGPSCompass_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance_to_goal(0.0)
    , angle_to_goal(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _distance_to_goal_type;
  _distance_to_goal_type distance_to_goal;

   typedef double _angle_to_goal_type;
  _angle_to_goal_type angle_to_goal;





  typedef boost::shared_ptr< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> const> ConstPtr;

}; // struct PointGoalWithGPSCompass_

typedef ::ros_x_habitat::PointGoalWithGPSCompass_<std::allocator<void> > PointGoalWithGPSCompass;

typedef boost::shared_ptr< ::ros_x_habitat::PointGoalWithGPSCompass > PointGoalWithGPSCompassPtr;
typedef boost::shared_ptr< ::ros_x_habitat::PointGoalWithGPSCompass const> PointGoalWithGPSCompassConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator1> & lhs, const ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.distance_to_goal == rhs.distance_to_goal &&
    lhs.angle_to_goal == rhs.angle_to_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator1> & lhs, const ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_x_habitat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1c2ae08f20a219947d5152f75072a85";
  }

  static const char* value(const ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1c2ae08f20a2199ULL;
  static const uint64_t static_value2 = 0x47d5152f75072a85ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_x_habitat/PointGoalWithGPSCompass";
  }

  static const char* value(const ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A representation of readings from Habitat's POINTGOAL_WITH_GPS_COMPASS sensor\n"
"\n"
"Header header\n"
"float64 distance_to_goal\n"
"float64 angle_to_goal # in radians\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance_to_goal);
      stream.next(m.angle_to_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointGoalWithGPSCompass_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_x_habitat::PointGoalWithGPSCompass_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance_to_goal: ";
    Printer<double>::stream(s, indent + "  ", v.distance_to_goal);
    s << indent << "angle_to_goal: ";
    Printer<double>::stream(s, indent + "  ", v.angle_to_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_X_HABITAT_MESSAGE_POINTGOALWITHGPSCOMPASS_H
