// Generated by gencpp from file ros_x_habitat/ResetAgent.msg
// DO NOT EDIT!


#ifndef ROS_X_HABITAT_MESSAGE_RESETAGENT_H
#define ROS_X_HABITAT_MESSAGE_RESETAGENT_H

#include <ros/service_traits.h>


#include <ros_x_habitat/ResetAgentRequest.h>
#include <ros_x_habitat/ResetAgentResponse.h>


namespace ros_x_habitat
{

struct ResetAgent
{

typedef ResetAgentRequest Request;
typedef ResetAgentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetAgent
} // namespace ros_x_habitat


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_x_habitat::ResetAgent > {
  static const char* value()
  {
    return "ce8257351a1f8b1ef5fb3350a09efd5a";
  }

  static const char* value(const ::ros_x_habitat::ResetAgent&) { return value(); }
};

template<>
struct DataType< ::ros_x_habitat::ResetAgent > {
  static const char* value()
  {
    return "ros_x_habitat/ResetAgent";
  }

  static const char* value(const ::ros_x_habitat::ResetAgent&) { return value(); }
};


// service_traits::MD5Sum< ::ros_x_habitat::ResetAgentRequest> should match
// service_traits::MD5Sum< ::ros_x_habitat::ResetAgent >
template<>
struct MD5Sum< ::ros_x_habitat::ResetAgentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_x_habitat::ResetAgent >::value();
  }
  static const char* value(const ::ros_x_habitat::ResetAgentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_x_habitat::ResetAgentRequest> should match
// service_traits::DataType< ::ros_x_habitat::ResetAgent >
template<>
struct DataType< ::ros_x_habitat::ResetAgentRequest>
{
  static const char* value()
  {
    return DataType< ::ros_x_habitat::ResetAgent >::value();
  }
  static const char* value(const ::ros_x_habitat::ResetAgentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_x_habitat::ResetAgentResponse> should match
// service_traits::MD5Sum< ::ros_x_habitat::ResetAgent >
template<>
struct MD5Sum< ::ros_x_habitat::ResetAgentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_x_habitat::ResetAgent >::value();
  }
  static const char* value(const ::ros_x_habitat::ResetAgentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_x_habitat::ResetAgentResponse> should match
// service_traits::DataType< ::ros_x_habitat::ResetAgent >
template<>
struct DataType< ::ros_x_habitat::ResetAgentResponse>
{
  static const char* value()
  {
    return DataType< ::ros_x_habitat::ResetAgent >::value();
  }
  static const char* value(const ::ros_x_habitat::ResetAgentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_X_HABITAT_MESSAGE_RESETAGENT_H
