// Generated by gencpp from file ros_x_habitat/ResetAgentResponse.msg
// DO NOT EDIT!


#ifndef ROS_X_HABITAT_MESSAGE_RESETAGENTRESPONSE_H
#define ROS_X_HABITAT_MESSAGE_RESETAGENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_x_habitat
{
template <class ContainerAllocator>
struct ResetAgentResponse_
{
  typedef ResetAgentResponse_<ContainerAllocator> Type;

  ResetAgentResponse_()
    : done(false)  {
    }
  ResetAgentResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetAgentResponse_

typedef ::ros_x_habitat::ResetAgentResponse_<std::allocator<void> > ResetAgentResponse;

typedef boost::shared_ptr< ::ros_x_habitat::ResetAgentResponse > ResetAgentResponsePtr;
typedef boost::shared_ptr< ::ros_x_habitat::ResetAgentResponse const> ResetAgentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator1> & lhs, const ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator1> & lhs, const ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_x_habitat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_x_habitat/ResetAgentResponse";
  }

  static const char* value(const ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n"
;
  }

  static const char* value(const ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetAgentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_x_habitat::ResetAgentResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_X_HABITAT_MESSAGE_RESETAGENTRESPONSE_H
