!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 1.0
  acc_lim_trans: 0.1
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 20.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 1.0
      acc_lim_trans: 0.1
      acc_lim_x: 1.0
      acc_lim_y: 1.0
      angular_sim_granularity: 0.1
      forward_point_distance: 0.325
      goal_distance_bias: 20.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_scaling_factor: 0.2
      max_vel_theta: 0.45
      max_vel_trans: 0.3
      max_vel_x: 0.35
      max_vel_y: 0.25
      min_vel_theta: 0.01
      min_vel_trans: 0.1
      min_vel_x: -0.25
      min_vel_y: -0.25
      name: Default
      occdist_scale: 0.02
      oscillation_reset_angle: 0.2
      oscillation_reset_dist: 0.05
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      path_distance_bias: 32.0
      prune_plan: false
      restore_defaults: false
      scaling_speed: 0.25
      sim_granularity: 0.025
      sim_time: 4.0
      state: true
      stop_time_buffer: 0.2
      theta_stopped_vel: 0.1
      trans_stopped_vel: 0.1
      twirling_scale: 0.0
      type: ''
      use_dwa: true
      vth_samples: 40
      vx_samples: 20
      vy_samples: 20
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.25
    state: []
  max_scaling_factor: 0.2
  max_vel_theta: 0.45
  max_vel_trans: 0.3
  max_vel_x: 0.35
  max_vel_y: 0.25
  min_vel_theta: 0.01
  min_vel_trans: 0.1
  min_vel_x: -0.25
  min_vel_y: -0.25
  occdist_scale: 0.02
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 32.0
  prune_plan: false
  restore_defaults: false
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 4.0
  stop_time_buffer: 0.2
  theta_stopped_vel: 0.1
  trans_stopped_vel: 0.1
  twirling_scale: 0.0
  use_dwa: true
  vth_samples: 40
  vx_samples: 20
  vy_samples: 20
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.25
state: []
